name: Phishing Detection CI

on:
  push:
    branches: [ "main" ,"master"]
  pull_request:
    branches: [ "main" ,"master"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ML tests
      run: |
        pytest ml/tests

    - name: Django system check
      run: |
        cd config
        python manage.py check
